<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>gm</groupId>
    <artifactId>jta</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>JavaTransactionApi</name>
    <packaging>war</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.source>21</maven.compiler.source>
        <junit.version>5.11.0</junit.version>
    </properties>

    <dependencies>
        <!-- ==================== JAKARTA EE API (SERVER) ==================== -->
        <!-- full API Jakarta EE 10, includes Persistence, Transaction,          -->
        <!-- Servlet, EJB, CDI and more... WildFly server provides on execution  -->
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>10.0.0</version>
            <scope>provided</scope>
        </dependency>
        <!-- ==================== DEPENDENCY INJECTION ==================== -->
        <!-- CDI (Contexts and Dependency Injection). Enable @Inject, @Named, @ApplicationScoped, etc.-->
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <version>4.1.0</version>
            <scope>provided</scope>
        </dependency>
        <!-- ==================== EJB (ENTERPRISE JAVA BEANS) ================== -->
        <!-- API for business components. Enable @Stateless, @Stateful, @Singleton -->
        <dependency>
            <groupId>jakarta.ejb</groupId>
            <artifactId>jakarta.ejb-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>
        <!-- ==================== WEB LAYER ===================================== -->
        <!-- Servlets API. Enable HttpServlet, @WebServlet, HttpServletRequest/Response -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.1.0</version>
            <scope>provided</scope>
        </dependency>
        <!-- Jakarta Faces (JSF) API. Enable view components (.xhtml) -->
        <dependency>
            <groupId>jakarta.faces</groupId>
            <artifactId>jakarta.faces-api</artifactId>
            <version>4.1.0</version>
            <scope>provided</scope>
        </dependency>
        <!-- JSTL for JSP. Enable tags <c:forEach>, <c:if>, ${expressions} on .jsp files. Embedded on WAR -->
        <dependency>
            <groupId>org.glassfish.web</groupId>
            <artifactId>jakarta.servlet.jsp.jstl</artifactId>
            <version>3.0.1</version>
        </dependency>
        <!-- ==================== PERSISTENCE ================================= -->
        <!-- JPA (EclipseLink) implementation. Process Entities -->
        <!-- @Entity, execute JPQL y manage EntityManager, defined on persistence.xml. -->
        <!-- It's included on WAR because WildFly use Hibernate by default y in here EclipseLink is forced-->
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>4.0.2</version>
        </dependency>
        <!-- ==================== DATABASE ================================ -->
        <!-- Driver JDBC of MySQL. Allos physical connection to db defined on persistence.xml -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>9.1.0</version>
        </dependency>
        <!-- LOGGING -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.24.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.24.3</version>
        </dependency>
    </dependencies>



    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
            </plugin>
        </plugins>
    </build>
</project>