package wsclient.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-01-31T20:52:52.918-06:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "AddServiceImplService",
                  wsdlLocation = "http://localhost:8080/sum/AddServiceImpl?wsdl",
                  targetNamespace = "http://beans.sum.ws.jax.gm/")
public class AddServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://beans.sum.ws.jax.gm/", "AddServiceImplService");
    public static final QName AddServiceImplPort = new QName("http://beans.sum.ws.jax.gm/", "AddServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/sum/AddServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AddServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/sum/AddServiceImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AddServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AddServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AddServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AddServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AddServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     *
     * @return
     *     returns AddServiceWs
     */
    @WebEndpoint(name = "AddServiceImplPort")
    public AddServiceWs getAddServiceImplPort() {
        return super.getPort(AddServiceImplPort, AddServiceWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddServiceWs
     */
    @WebEndpoint(name = "AddServiceImplPort")
    public AddServiceWs getAddServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AddServiceImplPort, AddServiceWs.class, features);
    }

}
