package wsclient.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-01-31T20:52:52.879-06:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://beans.sum.ws.jax.gm/", name = "AddServiceWs")
@XmlSeeAlso({ObjectFactory.class})
public interface AddServiceWs {

    @WebMethod
    @RequestWrapper(localName = "sum", targetNamespace = "http://beans.sum.ws.jax.gm/", className = "wsclient.service.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://beans.sum.ws.jax.gm/", className = "wsclient.service.SumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sum(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
