package wsclient.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-02-01T12:40:39.802-06:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://service.jta.gm/", name = "PersonServiceWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonServiceWs {

    @WebMethod
    @RequestWrapper(localName = "listPersons", targetNamespace = "http://service.jta.gm/", className = "wsclient.service.ListPersons")
    @ResponseWrapper(localName = "listPersonsResponse", targetNamespace = "http://service.jta.gm/", className = "wsclient.service.ListPersonsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wsclient.service.Person> listPersons()
;
}
